import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model, Types } from 'mongoose';
import { Attendance } from './entity/attendance.entity';

@Injectable()
export class AttendanceService {
    constructor(
        @InjectModel(Attendance.name) private attendanceModel: Model<Attendance>
    ) { }

    async markAttendance(userId: string, status: string = 'present', remarks?: string) {
        const today = new Date();
        today.setHours(0, 0, 0, 0);

        try {
            const existing = await this.attendanceModel.findOne({ userId: new Types.ObjectId(userId), date: today });

            if (existing) {
                return {
                    success: true,
                    message: 'Attendance already marked for today',
                    data: existing
                };
            }

            const newAttendance = new this.attendanceModel({
                userId: new Types.ObjectId(userId),
                date: today,
                status,
                loginTime: new Date(),
                remarks
            });

            const data = await newAttendance.save();
            return {
                success: true,
                message: 'Attendance marked successfully',
                data
            };
        } catch (error) {
            return {
                success: false,
                message: error.message || 'Error marking attendance',
                data: null
            };
        }
    }

    async getMonthAttendance(userId: string, year: number, month: number) {
        // month is 1-indexed (1-12)
        const startDate = new Date(year, month - 1, 1);
        const endDate = new Date(year, month, 0); // Last day of the month

        try {
            // Fetch existing attendance records
            const existingRecords = await this.attendanceModel.find({
                userId: new Types.ObjectId(userId),
                date: { $gte: startDate, $lte: endDate }
            }).exec();

            const attendanceMap = new Map();
            existingRecords.forEach(rec => {
                attendanceMap.set(rec.date.toDateString(), rec);
            });

            const fullMonthData: any[] = [];
            const today = new Date();
            today.setHours(0, 0, 0, 0);

            for (let d = new Date(startDate); d <= endDate; d.setDate(d.getDate() + 1)) {
                const dateString = d.toDateString();
                const dayOfWeek = d.getDay(); // 0 is Sunday

                if (attendanceMap.has(dateString)) {
                    fullMonthData.push(attendanceMap.get(dateString));
                } else {
                    let status = 'absent';
                    if (dayOfWeek === 0) {
                        status = 'holiday'; // Sunday is holiday
                    } else if (d > today) {
                        status = 'upcoming'; // Don't mark future days as absent yet
                    }

                    fullMonthData.push({
                        date: new Date(d),
                        status: status,
                        isAutoGenerated: true
                    });
                }
            }

            return {
                success: true,
                message: 'Monthly attendance fetched successfully',
                data: fullMonthData
            };
        } catch (error) {
            return {
                success: false,
                message: error.message || 'Error fetching attendance',
                data: null
            };
        }
    }
}
